### ISSUE TITLE
Ruby < 2.1.0 Compatibility

### ISSUE THREAD

**Issue by joshuabach** [janlelis/unicode-display_width#18]
Your gemspece specifies compatibility with any Ruby >= 1.9.3, but this library is not, in fact, compatible with Ruby 1.9.3, because of this line in lib/unicode/display_width/index.rb:

```ruby
require 'rubygems/util'
[...]
```

The file `rubygems/util.rb` is not included in the rubygems bundled with the 1.9.3 stdlib, but was only added somewhere between 2.0.0 and 2.1.0.

As noted in #17, this `require` is not actually required and the simplest solution would be to remove the rubygems dependency alltogether. Otherwise, you should increase the version constraint in your gemspec.

Thanks!

**Comment by janlelis** [comment]
I've just released v1.3.3 which removes this line and replaces it with direct zlib based implementation.

Please re-open if problem persists.
