### ISSUE TITLE
Print width of "\u{2E3A}" and "\u{2E3B}"

### ISSUE THREAD

**Issue by kuerbis** [janlelis/unicode-display_width#23]
As far as I can see*, the graphic character width of "\u{2E3A}" and "\u{2E3B}" are 2 and 3, but the print width in the terminal is 1.

    #!/usr/bin/ruby

    puts "|" + "-"        * 6 + "|||";
    puts "|" + "\u{2E3B}" * 6 + "|||";
    puts "|" + "\u{0bf8}" * 6 + "|||";

    puts "\n";
    puts "|" + "\u{2E3B}"  + " " * 3 + "|||";
    puts "|" + "\u{0bf8}"  + " " * 3 + "|||";

\* Deepin Terminal, GNOME-Terminal, Guake Terminal, Kitty, Konsole, LXTerminal, Sakura, Terminal, Terminator, Tilda, Xfce-Terminal, XTerm, Yakuake

**Comment by janlelis** [comment]
Hi @kuerbis,
thanks for bringing this up. Do you have some more info / links on the different methods of measuring width (graphic width vs print width)? Seems to me like it is treated incorrectly by the terminal emulators, but I would like to know more about this.

**Comment by janlelis** [comment]
Closing; should probably be fixed directly in the terminal emulators
