### ISSUE TITLE
String#display_width returns 1 for byte order mark

### ISSUE THREAD

**Issue by jonas054** [janlelis/unicode-display_width#3]
For a UTF-8 encoded BOM (codepoint U+FEFF) `"\xef\xbb\xbf".display_width` returns `1`. I expect it to be `0` as it is an invisible character.

**Comment by janlelis** [comment]
I'll research a way to deal with this an similar codepoints.

**Comment by janlelis** [comment]
Fixed with 1.0.0: `"\uFEFF".display_width #=> 0`

**Comment by jonas054** [comment]
:+1: Thanks!
