### ISSUE TITLE
Invalid gemspec

### ISSUE THREAD

**Issue by nicovanniekerk** [janlelis/unicode-display_width#8]
Good day,

I have just redone my dev pc, with windows 10. and upon installing gems i received an error related to unicode-display complaining about an invalid gemspec.

error: 
Invalid gemspec in [C:/Ruby193/lib/ruby/gems/1.9.1/specifications/unicode-display_width-1.0.3.gemspec]: Illformed requirement ["< 3.0.0, >= 1.9.3"]

The gem i am trying to install is rubocop that is depends on this.

Please advise.
Thank you
Nico van Niekerk

**Comment by sathlan** [comment]
Hi,

I have the same issue.  Including this fix https://github.com/janlelis/unicode-display_width/commit/79bea87c26516f64df0901d56a71c4a937f8f9b0 and releasing a new version would help I guess.

Regards,

**Comment by janlelis** [comment]
Will do (later this week)

**Comment by sathlan** [comment]
Nice, thanks.

**Comment by nicovanniekerk** [comment]
Thanks @janlelis please keep us posted

**Comment by janlelis** [comment]
I just released 1.0.4 which should fix this issue.
